server:
  port: 80
logging:
  level:
    com.ngmj.towechat.mapper: info
spring:
  mvc:
    throw-exception-if-no-handler-found: true
toWechat:
  app:
    token: niangumujing
    defaultMaxChars: 400
    platform: aliyun
  aliyun:
    apiKey: sk-1ae0d58b66db49b39139f6551bc5826b
    model: deepseek-r1